artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://www.kaggle.com/api/v1/datasets/download/mohamedhanyyy/chest-ctscan-images
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path : artifacts/prepare_base_model/model.keras
  updated_base_model_path : artifacts/prepare_base_model/base_model_updated.keras
  updated_base_model_png_path : artifacts/prepare_base_model/model_summary_image.png